-- MySQL Script generated by MySQL Workbench
-- Sun Dec 27 17:38:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Decimo` DEFAULT CHARACTER SET utf8 ;
USE `Decimo` ;

-- -----------------------------------------------------
-- Table `Decimo`.`Sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Sport` (
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Squadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Squadra` (
  `idsquadra` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Sport_nome1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsquadra`),
  CONSTRAINT `fk_Squadra_Sport2`
    FOREIGN KEY (`Sport_nome1`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Voto` (
  `idVoto` INT NOT NULL,
  `voto` INT NOT NULL,
  PRIMARY KEY (`idVoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Utente` (
  `username` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `organizzatore` TINYINT NULL,
  `giocatore` TINYINT NULL,
  `idsquadra` INT NULL,
  `Voto_idVoto` INT NULL,
  `Sport_nome` VARCHAR(45) NULL,
  `nascita` DATE NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `id`
    FOREIGN KEY (`idsquadra`)
    REFERENCES `Decimo`.`Squadra` (`idsquadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_Voto1`
    FOREIGN KEY (`Voto_idVoto`)
    REFERENCES `Decimo`.`Voto` (`idVoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_Sport1`
    FOREIGN KEY (`Sport_nome`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Notifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Notifica` (
  `idNotifica` INT NOT NULL,
  `Utente_username` VARCHAR(45) NULL,
  `testo` VARCHAR(500) NULL,
  PRIMARY KEY (`idNotifica`),
  CONSTRAINT `fk_Notifica_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Titolare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Titolare` (
  `Utente_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Utente_username`),
  CONSTRAINT `fk_Titolare_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Struttura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Struttura` (
  `idStruttura` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(45) NOT NULL,
  `giornochiusura` VARCHAR(8) NULL,
  `apertura` TIME NOT NULL,
  `chiusura` TIME NOT NULL,
  `citta` VARCHAR(45) NOT NULL,
  `Sport_nome` VARCHAR(45) NOT NULL,
  `Titolare_Utente_username` VARCHAR(45) NOT NULL,
  `Utente_username` VARCHAR(45) NULL,
  PRIMARY KEY (`idStruttura`, `Titolare_Utente_username`),
  CONSTRAINT `sport`
    FOREIGN KEY (`Sport_nome`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `titolare`
    FOREIGN KEY (`Titolare_Utente_username`)
    REFERENCES `Decimo`.`Titolare` (`Utente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Struttura_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`torneo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`torneo` (
  `idtorneo` INT NOT NULL,
  `Utente_username` VARCHAR(45) NOT NULL,
  `Struttura` INT NOT NULL,
  `Struttura_Titolare_Utente_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtorneo`),
  CONSTRAINT `fk_torneo_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_Struttura1`
    FOREIGN KEY (`Struttura` , `Struttura_Titolare_Utente_username`)
    REFERENCES `Decimo`.`Struttura` (`idStruttura` , `Titolare_Utente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO sport (nome) VALUES ('Basket');
INSERT INTO sport (nome) VALUES ('Calcetto');
INSERT INTO sport (nome) VALUES ('Pallavolo');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
