-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 18:40:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Decimo` ;

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Decimo` DEFAULT CHARACTER SET utf8 ;
USE `Decimo` ;

-- -----------------------------------------------------
-- Table `Decimo`.`Sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Sport` (
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Squadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Squadra` (
  `idsquadra` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Sport_nome1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsquadra`),
  CONSTRAINT `fk_Squadra_Sport2`
    FOREIGN KEY (`Sport_nome1`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Voto` (
  `idVoto` INT NOT NULL,
  `voto` INT NOT NULL,
  PRIMARY KEY (`idVoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`regione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`regione` (
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`citta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`citta` (
  `nome` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(2) NULL,
  `regione_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`),
  CONSTRAINT `fk_citta_regione1`
    FOREIGN KEY (`regione_nome`)
    REFERENCES `Decimo`.`regione` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Utente` (
  `username` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `organizzatore` BIT NULL DEFAULT false,
  `giocatore` BIT NULL DEFAULT false,
  `idsquadra` INT NULL,
  `Voto_idVoto` INT NULL,
  `Sport_nome` VARCHAR(45) NULL,
  `nascita` DATE NOT NULL,
  `citta_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `id`
    FOREIGN KEY (`idsquadra`)
    REFERENCES `Decimo`.`Squadra` (`idsquadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_Voto1`
    FOREIGN KEY (`Voto_idVoto`)
    REFERENCES `Decimo`.`Voto` (`idVoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_Sport1`
    FOREIGN KEY (`Sport_nome`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_citta1`
    FOREIGN KEY (`citta_nome`)
    REFERENCES `Decimo`.`citta` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Notifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Notifica` (
  `idNotifica` INT NOT NULL,
  `Utente_username` VARCHAR(45) NULL,
  `testo` VARCHAR(500) NULL,
  PRIMARY KEY (`idNotifica`),
  CONSTRAINT `fk_Notifica_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Titolare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Titolare` (
  `Utente_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Utente_username`),
  CONSTRAINT `fk_Titolare_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Struttura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`Struttura` (
  `idStruttura` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(45) NOT NULL,
  `giornochiusura` VARCHAR(8) NULL,
  `apertura` TIME NOT NULL,
  `chiusura` TIME NOT NULL,
  `Sport_nome` VARCHAR(45) NOT NULL,
  `Titolare_Utente_username` VARCHAR(45) NOT NULL,
  `Utente_username` VARCHAR(45) NULL,
  `spogliatoio` BIT NOT NULL DEFAULT false,
  `citta_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStruttura`, `Titolare_Utente_username`),
  CONSTRAINT `sport`
    FOREIGN KEY (`Sport_nome`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `titolare`
    FOREIGN KEY (`Titolare_Utente_username`)
    REFERENCES `Decimo`.`Titolare` (`Utente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Struttura_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Struttura_citta1`
    FOREIGN KEY (`citta_nome`)
    REFERENCES `Decimo`.`citta` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`torneo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`torneo` (
  `idtorneo` INT NOT NULL,
  `Utente_username` VARCHAR(45) NOT NULL,
  `Struttura` INT NOT NULL,
  `Struttura_Titolare_Utente_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtorneo`),
  CONSTRAINT `fk_torneo_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_Struttura1`
    FOREIGN KEY (`Struttura` , `Struttura_Titolare_Utente_username`)
    REFERENCES `Decimo`.`Struttura` (`idStruttura` , `Titolare_Utente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`partita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`partita` (
  `idpartita` INT NOT NULL AUTO_INCREMENT,
  `punteggioCasa` INT NOT NULL DEFAULT 0,
  `punteggioOspite` INT NOT NULL DEFAULT 0,
  `sport` VARCHAR(45) NOT NULL,
  `citta_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpartita`),
  CONSTRAINT `fk_partita_Sport1`
    FOREIGN KEY (`sport`)
    REFERENCES `Decimo`.`Sport` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partita_citta1`
    FOREIGN KEY (`citta_nome`)
    REFERENCES `Decimo`.`citta` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`partecipazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`partecipazione` (
  `partita_idpartita` INT NOT NULL,
  `Utente_username` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`partita_idpartita`, `Utente_username`),
  CONSTRAINT `fk_partita_has_Utente_partita1`
    FOREIGN KEY (`partita_idpartita`)
    REFERENCES `Decimo`.`partita` (`idpartita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partita_has_Utente_Utente1`
    FOREIGN KEY (`Utente_username`)
    REFERENCES `Decimo`.`Utente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`disputa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`disputa` (
  `partita_idpartita` INT NOT NULL,
  `Squadra_idsquadra` INT NOT NULL,
  PRIMARY KEY (`partita_idpartita`, `Squadra_idsquadra`),
  CONSTRAINT `fk_partita_has_Squadra_partita1`
    FOREIGN KEY (`partita_idpartita`)
    REFERENCES `Decimo`.`partita` (`idpartita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partita_has_Squadra_Squadra1`
    FOREIGN KEY (`Squadra_idsquadra`)
    REFERENCES `Decimo`.`Squadra` (`idsquadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`ospita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decimo`.`ospita` (
  `partita_idpartita` INT NOT NULL,
  `Struttura_idStruttura` INT NOT NULL,
  `Struttura_Titolare_Utente_username` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_partita_has_Struttura_partita1`
    FOREIGN KEY (`partita_idpartita`)
    REFERENCES `Decimo`.`partita` (`idpartita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partita_has_Struttura_Struttura1`
    FOREIGN KEY (`Struttura_idStruttura` , `Struttura_Titolare_Utente_username`)
    REFERENCES `Decimo`.`Struttura` (`idStruttura` , `Titolare_Utente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Decimo`.`Sport`
-- -----------------------------------------------------
START TRANSACTION;
USE `Decimo`;
INSERT INTO `Decimo`.`Sport` (`nome`) VALUES ('Calcetto');
INSERT INTO `Decimo`.`Sport` (`nome`) VALUES ('Basket');
INSERT INTO `Decimo`.`Sport` (`nome`) VALUES ('Pallavolo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Decimo`.`regione`
-- -----------------------------------------------------
START TRANSACTION;
USE `Decimo`;
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Molise');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Valle d\'Aosta');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Piemonte');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Liguria');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Lombardia');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Trentino-Alto Adige');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Veneto');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Friuli-Venezia Giulia');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Emilia Romagna');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Toscana');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Umbria');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Marche');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Lazio');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Abruzzo');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Campania');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Puglia');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Basilicata');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Calabria');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Sicilia ');
INSERT INTO `Decimo`.`regione` (`nome`) VALUES ('Sardegna ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Decimo`.`citta`
-- -----------------------------------------------------
START TRANSACTION;
USE `Decimo`;
INSERT INTO `Decimo`.`citta` (`nome`, `provincia`, `regione_nome`) VALUES ('Roma', 'RM', 'Lazio');
INSERT INTO `Decimo`.`citta` (`nome`, `provincia`, `regione_nome`) VALUES ('Torino', NULL, 'Piemonte');
INSERT INTO `Decimo`.`citta` (`nome`, `provincia`, `regione_nome`) VALUES ('Bologna', NULL, 'Emilia Romagna');
INSERT INTO `Decimo`.`citta` (`nome`, `provincia`, `regione_nome`) VALUES ('Napoli', NULL, 'Campania');

COMMIT;

