-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 00:13:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Decimo` ;

-- -----------------------------------------------------
-- Schema Decimo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Decimo` DEFAULT CHARACTER SET utf8 ;
USE `Decimo` ;

-- -----------------------------------------------------
-- Table `Decimo`.`Squadra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Decimo`.`Squadra` ;

CREATE TABLE IF NOT EXISTS `Decimo`.`Squadra` (
  `idsquadra` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsquadra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Decimo`.`Voto` ;

CREATE TABLE IF NOT EXISTS `Decimo`.`Voto` (
  `idVoto` INT NOT NULL,
  `voto` INT NOT NULL,
  PRIMARY KEY (`idVoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decimo`.`Utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Decimo`.`Utente` ;

CREATE TABLE IF NOT EXISTS `Decimo`.`Utente` (
  `username` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `organizzatore` TINYINT NULL,
  `giocatore` TINYINT NULL,
  `titolare` TINYINT NULL,
  `idsquadra` INT NULL,
  `Voto_idVoto` INT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `idsquadra`
    FOREIGN KEY (`idsquadra`)
    REFERENCES `Decimo`.`Squadra` (`idsquadra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idVoto`
    FOREIGN KEY (`Voto_idVoto`)
    REFERENCES `Decimo`.`Voto` (`idVoto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
